# Generated by Django 3.2 on 2022-04-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_author',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, null=True),
        ),
    ]
